// Kitchen Hub seed library (docs/39 "Seed library") — 50 family dinners balanced across
// Spanish / Dutch / Japanese / Italian / global (D3), kid-tested weeknight bias.
// Every ingredient carries a canonical Spanish name (`es`) for Mercadona SKU search.
// Nutrition values are per-serving ESTIMATES (flagged estimated:true). Photos are
// Wikimedia Commons thumbs downloaded into apps/web/public/recipes/ (see
// apps/web/public/recipes/ATTRIBUTION.md); a missing file degrades to a placeholder tile.
// Loaded ONCE on first boot by kitchen/store.ts (never overwrites user edits).

import type { Cuisine, Recipe, RecipeIngredient, RecipeStep, Season } from './types';

type SeedRecipe = Omit<Recipe, 'createdAt' | 'updatedAt' | 'source'>;

/** Ingredient shorthand: display name, canonical Spanish name, qty (per 4 servings), unit. */
function I(name: string, es: string, qty: number | null, unit: string, pantryStaple?: boolean): RecipeIngredient {
  return pantryStaple ? { name, es, qty, unit, pantryStaple: true } : { name, es, qty, unit };
}
const m = (text: string, timerSec?: number): RecipeStep => (timerSec ? { phase: 'mise', text, timerSec } : { phase: 'mise', text });
const c = (text: string, timerSec?: number): RecipeStep => (timerSec ? { phase: 'cook', text, timerSec } : { phase: 'cook', text });

interface SeedSpec {
  id: string;
  title: string;
  cuisine: Cuisine;
  prepMin: number;
  cookMin: number;
  tags: string[];
  kidScore?: number;
  season?: Season[];
  kcal: number;
  protein: number;
  carbs: number;
  fat: number;
  tools: string[];
  ingredients: RecipeIngredient[];
  steps: RecipeStep[];
}

function seed(s: SeedSpec): SeedRecipe {
  return {
    id: `seed-${s.id}`,
    title: s.title,
    photo: `/recipes/${s.id}.jpg`,
    servingsBase: 4,
    prepMin: s.prepMin,
    cookMin: s.cookMin,
    tags: s.tags,
    cuisine: s.cuisine,
    ...(s.kidScore != null ? { kidScore: s.kidScore } : {}),
    ...(s.season ? { season: s.season } : {}),
    nutrition: { kcal: s.kcal, proteinG: s.protein, carbsG: s.carbs, fatG: s.fat, estimated: true },
    tools: s.tools,
    ingredients: s.ingredients,
    steps: s.steps,
    lastCookedAt: null,
  };
}

export const SEED_RECIPES: SeedRecipe[] = [
  // ============================ SPANISH (11) ============================
  seed({
    id: 'paella-pollo', title: 'Paella de pollo y verduras', cuisine: 'spanish', prepMin: 15, cookMin: 35,
    tags: ['rice', 'one-pan'], kidScore: 0.8, kcal: 610, protein: 34, carbs: 61, fat: 24,
    tools: ['Paella pan (or wide skillet)', 'Chef knife', 'Grater'],
    ingredients: [
      I('Round/bomba rice', 'arroz redondo', 400, 'g'),
      I('Chicken thighs, boneless', 'contramuslos de pollo', 600, 'g'),
      I('Flat green beans', 'judía verde plana', 200, 'g'),
      I('Red pepper', 'pimiento rojo', 1, 'count'),
      I('Grated tomato', 'tomate rallado', 200, 'g'),
      I('Chicken stock', 'caldo de pollo', 1, 'l'),
      I('Olive oil', 'aceite de oliva virgen extra', 3, 'tbsp', true),
      I('Saffron / paella seasoning', 'azafrán', null, 'to taste', true),
    ],
    steps: [
      m('Cut the chicken into bite-size pieces; slice the pepper and trim the beans.'),
      m('Grate the tomato; warm the stock with the saffron.'),
      c('Brown the chicken in olive oil in the paella pan, then add pepper and beans for 5 min.', 300),
      c('Stir in the tomato, then the rice; toast 1 min and add the hot stock.'),
      c('Simmer 18 min without stirring until the rice is done; rest 5 min before serving.', 1080),
    ],
  }),
  seed({
    id: 'gazpacho-tortilla', title: 'Gazpacho + tortilla de patatas', cuisine: 'spanish', prepMin: 20, cookMin: 20,
    tags: ['veg', 'classic'], kidScore: 0.7, season: ['summer'], kcal: 480, protein: 16, carbs: 42, fat: 27,
    tools: ['Blender', 'Non-stick skillet', 'Large plate (for the flip)'],
    ingredients: [
      I('Ripe tomatoes', 'tomate pera', 1, 'kg'),
      I('Cucumber', 'pepino', 1, 'count'),
      I('Green pepper', 'pimiento verde', 1, 'count'),
      I('Potatoes', 'patata', 800, 'g'),
      I('Eggs', 'huevos', 6, 'count'),
      I('Onion', 'cebolla', 1, 'count'),
      I('Olive oil', 'aceite de oliva virgen extra', 6, 'tbsp', true),
      I('Sherry vinegar', 'vinagre de Jerez', 2, 'tbsp', true),
    ],
    steps: [
      m('Blend tomatoes, cucumber, green pepper, vinegar and 3 tbsp oil; chill the gazpacho.'),
      m('Peel and thinly slice the potatoes and onion; beat the eggs.'),
      c('Slowly fry potatoes and onion in oil until tender, ~12 min; drain.', 720),
      c('Mix with the eggs, set in the skillet ~4 min per side, flipping with a plate.', 240),
      c('Serve the tortilla in wedges with a glass of cold gazpacho.'),
    ],
  }),
  seed({
    id: 'gambas-ajillo', title: 'Gambas al ajillo + pan', cuisine: 'spanish', prepMin: 10, cookMin: 10,
    tags: ['fish', 'quick'], kidScore: 0.6, kcal: 430, protein: 28, carbs: 28, fat: 22,
    tools: ['Cazuela or small skillet', 'Chef knife'],
    ingredients: [
      I('Peeled prawns', 'gambas peladas', 500, 'g'),
      I('Garlic', 'ajo', 6, 'clove'),
      I('Dried chilli (guindilla)', 'guindilla', 1, 'count', true),
      I('Fresh parsley', 'perejil fresco', 1, 'bunch'),
      I('Baguette', 'barra de pan', 1, 'count'),
      I('Olive oil', 'aceite de oliva virgen extra', 6, 'tbsp', true),
    ],
    steps: [
      m('Slice the garlic; chop the parsley; pat the prawns dry.'),
      c('Warm the oil with garlic and chilli until it just sizzles.'),
      c('Add prawns, cook 2–3 min until pink; scatter parsley.', 180),
      c('Serve bubbling with plenty of bread for the oil.'),
    ],
  }),
  seed({
    id: 'lentejas-chorizo', title: 'Lentejas estofadas con chorizo', cuisine: 'spanish', prepMin: 10, cookMin: 40,
    tags: ['stew', 'legumes'], kidScore: 0.6, season: ['autumn', 'winter'], kcal: 520, protein: 27, carbs: 55, fat: 20,
    tools: ['Large pot', 'Chef knife'],
    ingredients: [
      I('Pardina lentils', 'lentejas pardinas', 350, 'g'),
      I('Cooking chorizo', 'chorizo para guisar', 200, 'g'),
      I('Carrots', 'zanahoria', 2, 'count'),
      I('Onion', 'cebolla', 1, 'count'),
      I('Potato', 'patata', 1, 'count'),
      I('Sweet paprika', 'pimentón dulce', 1, 'tsp', true),
      I('Bay leaf', 'laurel', 1, 'count', true),
      I('Olive oil', 'aceite de oliva virgen extra', 2, 'tbsp', true),
    ],
    steps: [
      m('Dice the onion, carrots and potato; slice the chorizo.'),
      c('Soften the onion in oil, add paprika, then everything else plus water to cover by 2 cm.'),
      c('Simmer gently ~35 min until the lentils are tender; season and serve.', 2100),
    ],
  }),
  seed({
    id: 'pollo-ajillo', title: 'Pollo al ajillo con arroz', cuisine: 'spanish', prepMin: 10, cookMin: 30,
    tags: ['chicken', 'rice'], kidScore: 0.8, kcal: 590, protein: 38, carbs: 48, fat: 25,
    tools: ['Deep skillet', 'Small pot'],
    ingredients: [
      I('Chicken pieces (bone-in)', 'pollo troceado', 1, 'kg'),
      I('Garlic', 'ajo', 8, 'clove'),
      I('White rice', 'arroz largo', 320, 'g'),
      I('Dry white wine', 'vino blanco de cocina', 150, 'ml'),
      I('Fresh rosemary/thyme', 'romero fresco', null, 'to taste', true),
      I('Olive oil', 'aceite de oliva virgen extra', 4, 'tbsp', true),
    ],
    steps: [
      m('Season the chicken; smash the garlic cloves (skin on).'),
      c('Brown the chicken well in oil with the garlic, ~12 min.', 720),
      c('Add wine and herbs, cover, simmer 15 min; cook the rice alongside.', 900),
      c('Serve the chicken and pan juices over the rice.'),
    ],
  }),
  seed({
    id: 'merluza-plancha', title: 'Merluza a la plancha con verduras', cuisine: 'spanish', prepMin: 10, cookMin: 20,
    tags: ['fish', 'light'], kidScore: 0.6, kcal: 380, protein: 34, carbs: 22, fat: 17,
    tools: ['Griddle or skillet', 'Oven tray'],
    ingredients: [
      I('Hake fillets', 'lomos de merluza', 600, 'g'),
      I('Courgette', 'calabacín', 1, 'count'),
      I('Cherry tomatoes', 'tomate cherry', 250, 'g'),
      I('Lemon', 'limón', 1, 'count'),
      I('Garlic', 'ajo', 2, 'clove', true),
      I('Olive oil', 'aceite de oliva virgen extra', 3, 'tbsp', true),
    ],
    steps: [
      m('Slice the courgette; halve the tomatoes; make a garlic-lemon-oil dressing.'),
      c('Roast or griddle the vegetables until charred at the edges, ~12 min.', 720),
      c('Sear the hake 3 min per side; spoon the dressing over and serve.', 360),
    ],
  }),
  seed({
    id: 'albondigas', title: 'Albóndigas en salsa con arroz', cuisine: 'spanish', prepMin: 20, cookMin: 25,
    tags: ['meat', 'kids-favourite'], kidScore: 0.9, kcal: 620, protein: 33, carbs: 52, fat: 29,
    tools: ['Large skillet', 'Mixing bowl', 'Small pot'],
    ingredients: [
      I('Mixed mince (beef/pork)', 'carne picada mixta', 600, 'g'),
      I('Egg', 'huevos', 1, 'count'),
      I('Breadcrumbs', 'pan rallado', 60, 'g', true),
      I('Crushed tomato', 'tomate triturado', 400, 'g'),
      I('Onion', 'cebolla', 1, 'count'),
      I('White rice', 'arroz largo', 320, 'g'),
      I('Garlic', 'ajo', 2, 'clove', true),
      I('Olive oil', 'aceite de oliva virgen extra', 3, 'tbsp', true),
    ],
    steps: [
      m('Mix mince, egg, breadcrumbs, minced garlic; roll ~20 meatballs.'),
      m('Dice the onion; start the rice.'),
      c('Brown the meatballs in oil; set aside.'),
      c('Soften the onion, add tomato, simmer 10 min; return meatballs for 8 min more.', 1080),
      c('Serve over rice.'),
    ],
  }),
  seed({
    id: 'pisto-huevo', title: 'Pisto con huevo frito', cuisine: 'spanish', prepMin: 15, cookMin: 30,
    tags: ['veg', 'one-pan'], kidScore: 0.5, season: ['summer', 'autumn'], kcal: 390, protein: 14, carbs: 26, fat: 26,
    tools: ['Wide skillet', 'Small skillet'],
    ingredients: [
      I('Courgette', 'calabacín', 2, 'count'),
      I('Aubergine', 'berenjena', 1, 'count'),
      I('Red pepper', 'pimiento rojo', 1, 'count'),
      I('Onion', 'cebolla', 1, 'count'),
      I('Crushed tomato', 'tomate triturado', 400, 'g'),
      I('Eggs', 'huevos', 4, 'count'),
      I('Olive oil', 'aceite de oliva virgen extra', 4, 'tbsp', true),
    ],
    steps: [
      m('Dice all the vegetables small and evenly.'),
      c('Fry onion and pepper 5 min, add courgette and aubergine 10 min more.', 900),
      c('Add tomato and simmer 12 min until thick.', 720),
      c('Fry an egg per person and serve on top of the pisto.'),
    ],
  }),
  seed({
    id: 'fideua', title: 'Fideuà de marisco', cuisine: 'spanish', prepMin: 15, cookMin: 25,
    tags: ['fish', 'one-pan'], kidScore: 0.6, kcal: 560, protein: 30, carbs: 58, fat: 22,
    tools: ['Paella pan (or wide skillet)', 'Chef knife'],
    ingredients: [
      I('Fideuà noodles', 'fideos de fideuà', 400, 'g'),
      I('Peeled prawns', 'gambas peladas', 300, 'g'),
      I('Squid rings', 'anillas de calamar', 250, 'g'),
      I('Fish stock', 'caldo de pescado', 1, 'l'),
      I('Grated tomato', 'tomate rallado', 150, 'g'),
      I('Garlic', 'ajo', 3, 'clove', true),
      I('Sweet paprika', 'pimentón dulce', 1, 'tsp', true),
      I('Olive oil', 'aceite de oliva virgen extra', 3, 'tbsp', true),
    ],
    steps: [
      m('Warm the stock; chop the garlic.'),
      c('Sear squid and prawns briefly; set the prawns aside.'),
      c('Fry garlic, paprika and tomato; toast the noodles 2 min in the sofrito.'),
      c('Add hot stock, simmer ~10 min; top with prawns for the last 3 min.', 600),
    ],
  }),
  seed({
    id: 'croquetas-ensalada', title: 'Croquetas de jamón con ensalada', cuisine: 'spanish', prepMin: 10, cookMin: 15,
    tags: ['quick', 'kids-favourite'], kidScore: 0.9, kcal: 540, protein: 18, carbs: 44, fat: 32,
    tools: ['Deep skillet', 'Salad bowl'],
    ingredients: [
      I('Ham croquettes (chilled)', 'croquetas de jamón', 24, 'count'),
      I('Mixed salad leaves', 'ensalada mezcla', 1, 'count'),
      I('Cherry tomatoes', 'tomate cherry', 250, 'g'),
      I('Cucumber', 'pepino', 1, 'count'),
      I('Olive oil', 'aceite de oliva virgen extra', 3, 'tbsp', true),
      I('Sherry vinegar', 'vinagre de Jerez', 1, 'tbsp', true),
    ],
    steps: [
      m('Dress the leaves, tomatoes and cucumber just before frying.'),
      c('Shallow-fry the croquettes in batches until deep golden, ~3 min each.', 180),
      c('Drain on paper and serve hot next to the salad.'),
    ],
  }),
  seed({
    id: 'salmorejo-flamenquin', title: 'Salmorejo + flamenquines', cuisine: 'spanish', prepMin: 20, cookMin: 15,
    tags: ['classic'], kidScore: 0.7, season: ['summer'], kcal: 640, protein: 28, carbs: 48, fat: 36,
    tools: ['Blender', 'Deep skillet'],
    ingredients: [
      I('Ripe tomatoes', 'tomate pera', 1, 'kg'),
      I('Day-old bread', 'pan de pueblo', 150, 'g'),
      I('Pork loin fillets', 'filetes de lomo de cerdo', 400, 'g'),
      I('Sliced serrano ham', 'jamón serrano en lonchas', 100, 'g'),
      I('Eggs', 'huevos', 3, 'count'),
      I('Breadcrumbs', 'pan rallado', 120, 'g', true),
      I('Garlic', 'ajo', 1, 'clove', true),
      I('Olive oil', 'aceite de oliva virgen extra', 150, 'ml', true),
    ],
    steps: [
      m('Blend tomatoes, soaked bread, garlic and oil until silky; chill the salmorejo.'),
      m('Roll each pork fillet around a slice of ham; egg-and-breadcrumb them.'),
      c('Fry the flamenquines until golden, ~4 min per batch.', 240),
      c('Serve with the cold salmorejo topped with chopped egg.'),
    ],
  }),

  // ============================ DUTCH (9) ============================
  seed({
    id: 'pannenkoeken', title: 'Pannenkoeken met spek en kaas', cuisine: 'dutch', prepMin: 10, cookMin: 25,
    tags: ['kids-favourite', 'quick'], kidScore: 1, kcal: 680, protein: 24, carbs: 66, fat: 34,
    tools: ['Non-stick skillet', 'Whisk', 'Ladle'],
    ingredients: [
      I('Flour', 'harina de trigo', 400, 'g', true),
      I('Milk', 'leche semidesnatada', 800, 'ml'),
      I('Eggs', 'huevos', 4, 'count'),
      I('Bacon strips', 'bacon en lonchas', 200, 'g'),
      I('Grated cheese', 'queso rallado gouda', 200, 'g'),
      I('Butter', 'mantequilla', 50, 'g', true),
      I('Syrup (stroop) or honey', 'miel', null, 'to taste', true),
    ],
    steps: [
      m('Whisk flour, milk, eggs and a pinch of salt into a smooth batter; rest 10 min.', 600),
      c('Lay 2–3 bacon strips in the pan, pour a ladle of batter over and cook until set.'),
      c('Flip, scatter cheese, cook until golden; repeat and keep a stack warm.'),
      c('Serve with syrup on the table — sweet + salty is the point.'),
    ],
  }),
  seed({
    id: 'hutspot', title: 'Hutspot met rookworst', cuisine: 'dutch', prepMin: 15, cookMin: 30,
    tags: ['stamppot', 'comfort'], kidScore: 0.8, season: ['autumn', 'winter'], kcal: 560, protein: 22, carbs: 52, fat: 29,
    tools: ['Large pot', 'Potato masher'],
    ingredients: [
      I('Potatoes', 'patata', 1.2, 'kg'),
      I('Carrots', 'zanahoria', 600, 'g'),
      I('Onions', 'cebolla', 2, 'count'),
      I('Smoked sausage', 'salchicha ahumada', 400, 'g'),
      I('Butter', 'mantequilla', 50, 'g', true),
      I('Milk', 'leche semidesnatada', 100, 'ml', true),
    ],
    steps: [
      m('Peel and chunk the potatoes, carrots and onions.'),
      c('Boil everything together ~20 min until tender; warm the sausage per its packet.', 1200),
      c('Drain, mash coarsely with butter and a splash of milk; season generously.'),
      c('Serve with thick slices of rookworst and mustard.'),
    ],
  }),
  seed({
    id: 'boerenkool', title: 'Boerenkoolstamppot met worst', cuisine: 'dutch', prepMin: 15, cookMin: 30,
    tags: ['stamppot', 'comfort'], kidScore: 0.6, season: ['winter'], kcal: 580, protein: 21, carbs: 55, fat: 30,
    tools: ['Large pot', 'Potato masher'],
    ingredients: [
      I('Potatoes', 'patata', 1.2, 'kg'),
      I('Curly kale, chopped', 'kale (col rizada)', 400, 'g'),
      I('Smoked sausage', 'salchicha ahumada', 400, 'g'),
      I('Bacon lardons', 'bacon en taquitos', 125, 'g'),
      I('Butter', 'mantequilla', 40, 'g', true),
      I('Mustard', 'mostaza', null, 'to taste', true),
    ],
    steps: [
      m('Peel and chunk the potatoes; rinse the kale.'),
      c('Boil potatoes with the kale on top ~20 min; crisp the lardons meanwhile.', 1200),
      c('Mash with butter, fold in the lardons; serve with sausage and mustard.'),
    ],
  }),
  seed({
    id: 'erwtensoep', title: 'Erwtensoep (snert) met roggebrood', cuisine: 'dutch', prepMin: 15, cookMin: 60,
    tags: ['soup', 'weekend'], kidScore: 0.5, season: ['winter'], kcal: 520, protein: 26, carbs: 58, fat: 20,
    tools: ['Big soup pot', 'Chef knife'],
    ingredients: [
      I('Split peas', 'guisantes secos partidos', 400, 'g'),
      I('Smoked sausage', 'salchicha ahumada', 300, 'g'),
      I('Leek', 'puerro', 1, 'count'),
      I('Carrots', 'zanahoria', 2, 'count'),
      I('Celeriac (or celery)', 'apio', 200, 'g'),
      I('Rye bread', 'pan de centeno', 1, 'count'),
      I('Bacon lardons', 'bacon en taquitos', 125, 'g'),
    ],
    steps: [
      m('Rinse the peas; dice all the vegetables.'),
      c('Simmer peas in 1.5 l water ~45 min until they fall apart, skimming once.', 2700),
      c('Add vegetables and lardons for 15 min; slice in the sausage to warm through.', 900),
      c('The spoon should stand up. Serve with rye bread.'),
    ],
  }),
  seed({
    id: 'kipsate', title: 'Kipsaté met friet', cuisine: 'dutch', prepMin: 15, cookMin: 25,
    tags: ['kids-favourite'], kidScore: 0.9, kcal: 720, protein: 38, carbs: 58, fat: 36,
    tools: ['Skewers', 'Grill pan', 'Oven tray', 'Small pot'],
    ingredients: [
      I('Chicken thighs, boneless', 'contramuslos de pollo', 600, 'g'),
      I('Oven fries', 'patatas fritas congeladas', 750, 'g'),
      I('Peanut butter', 'crema de cacahuete', 150, 'g'),
      I('Coconut milk', 'leche de coco', 200, 'ml'),
      I('Soy sauce', 'salsa de soja', 3, 'tbsp', true),
      I('Cucumber', 'pepino', 1, 'count'),
    ],
    steps: [
      m('Cube and skewer the chicken; marinate in 2 tbsp soy.'),
      m('Start the oven fries per the packet.'),
      c('Simmer peanut butter, coconut milk and soy into a satay sauce, 5 min.', 300),
      c('Grill the skewers ~10 min, turning; serve with fries, sauce and cucumber sticks.', 600),
    ],
  }),
  seed({
    id: 'gehaktballen', title: 'Gehaktballen met andijviestamppot', cuisine: 'dutch', prepMin: 20, cookMin: 30,
    tags: ['stamppot', 'comfort'], kidScore: 0.8, season: ['autumn', 'winter'], kcal: 640, protein: 30, carbs: 50, fat: 34,
    tools: ['Large pot', 'Skillet', 'Potato masher'],
    ingredients: [
      I('Mixed mince (beef/pork)', 'carne picada mixta', 600, 'g'),
      I('Potatoes', 'patata', 1.2, 'kg'),
      I('Escarole/endive, sliced', 'escarola', 300, 'g'),
      I('Egg', 'huevos', 1, 'count'),
      I('Breadcrumbs', 'pan rallado', 60, 'g', true),
      I('Butter', 'mantequilla', 60, 'g', true),
      I('Nutmeg', 'nuez moscada', null, 'to taste', true),
    ],
    steps: [
      m('Knead mince with egg, breadcrumbs, nutmeg; shape 4 big balls.'),
      c('Brown the balls all over in butter, then cover and cook gently 20 min.', 1200),
      c('Boil and mash the potatoes; fold the raw escarole through the hot mash.'),
      c('Serve a ball on the stamppot with the pan gravy.'),
    ],
  }),
  seed({
    id: 'witlof-ham-kaas', title: 'Witlof met ham en kaas uit de oven', cuisine: 'dutch', prepMin: 15, cookMin: 30,
    tags: ['oven', 'comfort'], kidScore: 0.5, season: ['winter'], kcal: 520, protein: 28, carbs: 34, fat: 30,
    tools: ['Oven dish', 'Large pot'],
    ingredients: [
      I('Chicory (witlof)', 'endivias', 8, 'count'),
      I('Cooked ham slices', 'jamón cocido en lonchas', 8, 'count'),
      I('Grated cheese', 'queso rallado gouda', 200, 'g'),
      I('Potatoes', 'patata', 800, 'g'),
      I('Milk', 'leche semidesnatada', 100, 'ml', true),
      I('Butter', 'mantequilla', 40, 'g', true),
    ],
    steps: [
      m('Halve the chicory; boil or steam 8 min and drain WELL.', 480),
      m('Boil and mash the potatoes with butter and milk.'),
      c('Wrap each chicory in ham, lay in the dish, cover with cheese.'),
      c('Bake at 200°C ~15 min until bubbling; serve on the mash.', 900),
    ],
  }),
  seed({
    id: 'nasi-goreng', title: 'Nasi goreng met spiegelei', cuisine: 'dutch', prepMin: 15, cookMin: 15,
    tags: ['rice', 'quick', 'indo'], kidScore: 0.8, kcal: 580, protein: 26, carbs: 62, fat: 25,
    tools: ['Wok', 'Small skillet', 'Rice cooker or pot'],
    ingredients: [
      I('Long-grain rice (day-old is best)', 'arroz largo', 320, 'g'),
      I('Chicken breast', 'pechuga de pollo', 400, 'g'),
      I('Nasi/bami vegetable mix', 'preparado de verduras para wok', 400, 'g'),
      I('Eggs', 'huevos', 4, 'count'),
      I('Sweet soy sauce (ketjap)', 'salsa de soja dulce', 4, 'tbsp'),
      I('Sambal or chilli paste', 'pasta de chile (sambal)', 1, 'tsp', true),
    ],
    steps: [
      m('Cook the rice ahead and cool it; dice the chicken.'),
      c('Stir-fry chicken hot and fast, add vegetables 3 min, then rice, ketjap and sambal.', 180),
      c('Fry an egg per person; serve sunny-side-up on the rice with prawn crackers if you have them.'),
    ],
  }),
  seed({
    id: 'kibbeling', title: 'Kibbeling met salade en friet', cuisine: 'dutch', prepMin: 15, cookMin: 20,
    tags: ['fish', 'kids-favourite'], kidScore: 0.8, kcal: 650, protein: 32, carbs: 55, fat: 33,
    tools: ['Deep skillet', 'Oven tray', 'Whisk'],
    ingredients: [
      I('Cod chunks', 'taquitos de bacalao (o merluza)', 600, 'g'),
      I('Flour', 'harina de trigo', 150, 'g', true),
      I('Sparkling water (cold)', 'agua con gas', 200, 'ml'),
      I('Oven fries', 'patatas fritas congeladas', 750, 'g'),
      I('Mixed salad leaves', 'ensalada mezcla', 1, 'count'),
      I('Garlic sauce or aioli', 'salsa alioli', 150, 'g'),
      I('Sunflower oil (for frying)', 'aceite de girasol', 500, 'ml', true),
    ],
    steps: [
      m('Start the fries; whisk flour, fizzy water and salt into a thin batter.'),
      m('Pat the fish dry and season with paprika-salt.'),
      c('Dip fish in batter and fry in 180°C oil ~4 min per batch until golden.', 240),
      c('Serve with fries, salad and the garlic sauce.'),
    ],
  }),

  // ============================ JAPANESE (10) ============================
  seed({
    id: 'katsu-curry', title: 'Chicken katsu curry', cuisine: 'japanese', prepMin: 15, cookMin: 30,
    tags: ['kids-favourite', 'rice'], kidScore: 1, kcal: 720, protein: 38, carbs: 72, fat: 30,
    tools: ['Skillet', 'Small pot', 'Rice cooker or pot'],
    ingredients: [
      I('Chicken breast', 'pechuga de pollo', 600, 'g'),
      I('Panko breadcrumbs', 'panko (pan rallado crujiente)', 200, 'g'),
      I('Japanese curry roux block', 'curry japonés en bloque', 1, 'count'),
      I('Short-grain rice', 'arroz redondo', 320, 'g'),
      I('Carrots', 'zanahoria', 2, 'count'),
      I('Onion', 'cebolla', 1, 'count'),
      I('Eggs', 'huevos', 2, 'count'),
      I('Flour', 'harina de trigo', 60, 'g', true),
      I('Sunflower oil (for frying)', 'aceite de girasol', 300, 'ml', true),
    ],
    steps: [
      m('Butterfly and flatten the chicken; set up flour → beaten egg → panko stations.'),
      m('Start the rice; simmer carrot + onion in 600 ml water 10 min, melt in the roux.', 600),
      c('Fry the cutlets ~4 min per side until deep golden; rest and slice.', 480),
      c('Serve sliced katsu on rice, sauce over one half.'),
    ],
  }),
  seed({
    id: 'yakitori-bowls', title: 'Yakitori bowls with rice', cuisine: 'japanese', prepMin: 20, cookMin: 20,
    tags: ['grill', 'rice'], kidScore: 0.8, kcal: 640, protein: 36, carbs: 64, fat: 24,
    tools: ['Skewers', 'Grill pan', 'Rice cooker or pot', 'Small pot'],
    ingredients: [
      I('Chicken thighs, boneless', 'contramuslos de pollo', 600, 'g'),
      I('Spring onions', 'cebolleta', 1, 'bunch'),
      I('Short-grain rice', 'arroz redondo', 320, 'g'),
      I('Soy sauce', 'salsa de soja', 100, 'ml', true),
      I('Mirin (or honey + water)', 'mirin', 100, 'ml'),
      I('Sugar', 'azúcar', 1, 'tbsp', true),
      I('Cucumber', 'pepino', 1, 'count'),
    ],
    steps: [
      m('Cube the chicken, cut the spring onion into 3 cm pieces, thread skewers alternating.'),
      m('Start the rice; boil soy + mirin + sugar into a glossy tare, 5 min.', 300),
      c('Grill the skewers ~12 min, turning and brushing with tare each turn.', 720),
      c('Serve over rice with quick-pickled cucumber.'),
    ],
  }),
  seed({
    id: 'miso-ramen', title: 'Miso ramen (weeknight)', cuisine: 'japanese', prepMin: 15, cookMin: 20,
    tags: ['soup', 'quick'], kidScore: 0.7, kcal: 590, protein: 30, carbs: 68, fat: 21,
    tools: ['Large pot', 'Small pot'],
    ingredients: [
      I('Ramen noodles', 'fideos ramen', 400, 'g'),
      I('Miso paste', 'pasta de miso', 4, 'tbsp'),
      I('Chicken stock', 'caldo de pollo', 1.5, 'l'),
      I('Eggs', 'huevos', 4, 'count'),
      I('Sweetcorn', 'maíz dulce', 150, 'g'),
      I('Spring onions', 'cebolleta', 1, 'bunch'),
      I('Cooked chicken or tofu', 'pechuga de pollo', 300, 'g'),
      I('Sesame oil', 'aceite de sésamo', 1, 'tbsp', true),
    ],
    steps: [
      m('Soft-boil the eggs 6½ min, peel; slice the spring onions.', 390),
      c('Heat the stock; whisk in miso off the boil.'),
      c('Cook noodles separately, divide into bowls, ladle soup over.'),
      c('Top with chicken, corn, egg halves, spring onion and a drop of sesame oil.'),
    ],
  }),
  seed({
    id: 'oyakodon', title: 'Oyakodon (chicken & egg rice bowl)', cuisine: 'japanese', prepMin: 10, cookMin: 20,
    tags: ['rice', 'quick', 'one-pan'], kidScore: 0.8, kcal: 560, protein: 34, carbs: 62, fat: 18,
    tools: ['Small skillet with lid', 'Rice cooker or pot'],
    ingredients: [
      I('Chicken thighs, boneless', 'contramuslos de pollo', 500, 'g'),
      I('Eggs', 'huevos', 6, 'count'),
      I('Onion', 'cebolla', 1, 'count'),
      I('Short-grain rice', 'arroz redondo', 320, 'g'),
      I('Soy sauce', 'salsa de soja', 4, 'tbsp', true),
      I('Mirin (or honey + water)', 'mirin', 4, 'tbsp'),
      I('Chicken stock', 'caldo de pollo', 200, 'ml'),
    ],
    steps: [
      m('Start the rice; slice the onion thin and the chicken into bite-size pieces.'),
      c('Simmer stock, soy and mirin with onion 3 min; add chicken and cook 6 min.', 360),
      c('Pour beaten eggs over in a spiral, lid on, 1–2 min until barely set.', 120),
      c('Slide over bowls of rice; scatter spring onion if you have it.'),
    ],
  }),
  seed({
    id: 'teriyaki-salmon', title: 'Teriyaki salmon with rice & broccoli', cuisine: 'japanese', prepMin: 10, cookMin: 20,
    tags: ['fish', 'quick'], kidScore: 0.7, kcal: 610, protein: 36, carbs: 58, fat: 25,
    tools: ['Skillet', 'Steamer or pot', 'Rice cooker or pot'],
    ingredients: [
      I('Salmon fillets', 'lomos de salmón', 4, 'count'),
      I('Broccoli', 'brócoli', 1, 'count'),
      I('Short-grain rice', 'arroz redondo', 320, 'g'),
      I('Soy sauce', 'salsa de soja', 4, 'tbsp', true),
      I('Mirin (or honey + water)', 'mirin', 3, 'tbsp'),
      I('Sugar', 'azúcar', 1, 'tbsp', true),
      I('Sesame seeds', 'sésamo tostado', 1, 'tbsp', true),
    ],
    steps: [
      m('Start the rice; cut the broccoli into florets; mix soy, mirin and sugar.'),
      c('Pan-sear the salmon skin-side down 4 min, flip for 2.', 360),
      c('Pour in the sauce and glaze, spooning over, 2 min; steam the broccoli meanwhile.', 120),
      c('Serve on rice, sauce over, sesame on top.'),
    ],
  }),
  seed({
    id: 'gyoza', title: 'Gyoza + gohan (potsticker night)', cuisine: 'japanese', prepMin: 10, cookMin: 20,
    tags: ['kids-favourite', 'quick'], kidScore: 0.9, kcal: 540, protein: 22, carbs: 66, fat: 20,
    tools: ['Non-stick skillet with lid', 'Rice cooker or pot'],
    ingredients: [
      I('Frozen gyoza', 'gyozas congeladas', 32, 'count'),
      I('Short-grain rice', 'arroz redondo', 320, 'g'),
      I('Edamame (frozen)', 'edamame congelado', 300, 'g'),
      I('Soy sauce', 'salsa de soja', 4, 'tbsp', true),
      I('Rice vinegar', 'vinagre de arroz', 2, 'tbsp', true),
      I('Sesame oil', 'aceite de sésamo', 1, 'tbsp', true),
    ],
    steps: [
      m('Start the rice; mix soy + vinegar + a drop of sesame for dipping.'),
      c('Fry gyoza flat-side down 2 min, add 100 ml water, lid on, steam 6 min.', 360),
      c('Uncover to crisp the bottoms; boil the edamame 4 min with salt.', 240),
      c('Serve everything family-style.'),
    ],
  }),
  seed({
    id: 'okonomiyaki', title: 'Okonomiyaki (cabbage pancakes)', cuisine: 'japanese', prepMin: 15, cookMin: 20,
    tags: ['veg-forward', 'fun'], kidScore: 0.7, kcal: 520, protein: 20, carbs: 52, fat: 26,
    tools: ['Non-stick skillet', 'Mixing bowl', 'Two spatulas'],
    ingredients: [
      I('White cabbage', 'col blanca', 500, 'g'),
      I('Flour', 'harina de trigo', 200, 'g', true),
      I('Eggs', 'huevos', 4, 'count'),
      I('Bacon strips', 'bacon en lonchas', 150, 'g'),
      I('Spring onions', 'cebolleta', 1, 'bunch'),
      I('Mayonnaise', 'mayonesa', null, 'to taste', true),
      I('Worcestershire/okonomi sauce', 'salsa Worcestershire', null, 'to taste', true),
    ],
    steps: [
      m('Shred the cabbage finely; slice the spring onions.'),
      m('Mix flour, eggs and 150 ml water; fold in cabbage and onions.'),
      c('Cook thick pancakes with bacon pressed on top, ~4 min per side.', 480),
      c('Zigzag with mayo + sauce; slice like a pizza.'),
    ],
  }),
  seed({
    id: 'karaage', title: 'Chicken karaage with rice & slaw', cuisine: 'japanese', prepMin: 20, cookMin: 15,
    tags: ['kids-favourite'], kidScore: 0.9, kcal: 660, protein: 36, carbs: 58, fat: 30,
    tools: ['Deep skillet', 'Rice cooker or pot', 'Mixing bowl'],
    ingredients: [
      I('Chicken thighs, boneless', 'contramuslos de pollo', 700, 'g'),
      I('Potato starch or cornflour', 'maicena', 100, 'g', true),
      I('Soy sauce', 'salsa de soja', 3, 'tbsp', true),
      I('Fresh ginger', 'jengibre fresco', 20, 'g'),
      I('Garlic', 'ajo', 2, 'clove', true),
      I('Short-grain rice', 'arroz redondo', 320, 'g'),
      I('White cabbage', 'col blanca', 300, 'g'),
      I('Sunflower oil (for frying)', 'aceite de girasol', 500, 'ml', true),
      I('Lemon', 'limón', 1, 'count'),
    ],
    steps: [
      m('Marinate chicken chunks in soy, grated ginger and garlic, 15 min.', 900),
      m('Start the rice; shred the cabbage for slaw.'),
      c('Toss chicken in starch; fry at 170°C ~4 min per batch, then a hot second fry for crunch.', 240),
      c('Serve with rice, slaw and lemon wedges.'),
    ],
  }),
  seed({
    id: 'yaki-udon', title: 'Yaki udon with pork & vegetables', cuisine: 'japanese', prepMin: 10, cookMin: 15,
    tags: ['noodles', 'quick'], kidScore: 0.8, kcal: 570, protein: 28, carbs: 64, fat: 22,
    tools: ['Wok', 'Tongs'],
    ingredients: [
      I('Udon noodles (fresh/vac-pack)', 'fideos udon', 600, 'g'),
      I('Pork loin strips', 'lomo de cerdo en tiras', 400, 'g'),
      I('Wok vegetable mix', 'preparado de verduras para wok', 400, 'g'),
      I('Soy sauce', 'salsa de soja', 3, 'tbsp', true),
      I('Oyster sauce', 'salsa de ostras', 2, 'tbsp'),
      I('Sesame oil', 'aceite de sésamo', 1, 'tbsp', true),
    ],
    steps: [
      m('Loosen the udon in warm water; mix soy + oyster sauce.'),
      c('Stir-fry the pork hot, 3 min; add vegetables 3 min more.', 180),
      c('Add noodles and sauce, toss 2 min; finish with sesame oil.', 120),
    ],
  }),
  seed({
    id: 'chirashi-bowls', title: 'Chirashi-style salmon rice bowls', cuisine: 'japanese', prepMin: 20, cookMin: 15,
    tags: ['fish', 'fresh'], kidScore: 0.6, season: ['summer'], kcal: 580, protein: 32, carbs: 62, fat: 21,
    tools: ['Rice cooker or pot', 'Sharp knife'],
    ingredients: [
      I('Sushi-grade or hot-smoked salmon', 'salmón ahumado', 300, 'g'),
      I('Short-grain rice', 'arroz redondo', 320, 'g'),
      I('Rice vinegar', 'vinagre de arroz', 4, 'tbsp', true),
      I('Avocado', 'aguacate', 2, 'count'),
      I('Cucumber', 'pepino', 1, 'count'),
      I('Nori sheets', 'alga nori', 2, 'count'),
      I('Sesame seeds', 'sésamo tostado', 1, 'tbsp', true),
      I('Soy sauce', 'salsa de soja', null, 'to taste', true),
    ],
    steps: [
      m('Cook the rice; season warm with vinegar + a pinch of sugar and salt, fan to cool.'),
      m('Slice salmon, avocado and cucumber; snip the nori.'),
      c('Assemble bowls: rice, toppings arranged in wedges, sesame + nori over.'),
      c('Serve with soy on the side.'),
    ],
  }),

  // ============================ ITALIAN (10) ============================
  seed({
    id: 'vongole', title: 'Spaghetti alle vongole', cuisine: 'italian', prepMin: 10, cookMin: 15,
    tags: ['pasta', 'fish', 'quick'], kidScore: 0.6, kcal: 560, protein: 24, carbs: 72, fat: 18,
    tools: ['Large pot', 'Wide skillet with lid'],
    ingredients: [
      I('Spaghetti', 'espaguetis', 400, 'g'),
      I('Fresh clams', 'almejas frescas', 800, 'g'),
      I('Garlic', 'ajo', 4, 'clove', true),
      I('Dry white wine', 'vino blanco de cocina', 150, 'ml'),
      I('Fresh parsley', 'perejil fresco', 1, 'bunch'),
      I('Olive oil', 'aceite de oliva virgen extra', 4, 'tbsp', true),
      I('Dried chilli (guindilla)', 'guindilla', 1, 'count', true),
    ],
    steps: [
      m('Purge the clams in salted water 20 min; slice garlic, chop parsley.', 1200),
      c('Cook spaghetti 1 min short of al dente.'),
      c('Sizzle garlic + chilli in oil, add clams and wine, lid on 3 min until open.', 180),
      c('Toss pasta through with parsley and a splash of pasta water.'),
    ],
  }),
  seed({
    id: 'pizza-night', title: 'Pizza night (homemade)', cuisine: 'italian', prepMin: 30, cookMin: 20,
    tags: ['kids-favourite', 'weekend', 'oven'], kidScore: 1, kcal: 820, protein: 32, carbs: 96, fat: 34,
    tools: ['Oven (max heat)', 'Baking trays', 'Rolling pin'],
    ingredients: [
      I('Pizza flour', 'harina de fuerza', 600, 'g'),
      I('Dry yeast', 'levadura seca de panadería', 7, 'g', true),
      I('Crushed tomato', 'tomate triturado', 400, 'g'),
      I('Mozzarella', 'mozzarella rallada', 400, 'g'),
      I('Toppings (ham, mushrooms…)', 'jamón cocido en lonchas', 200, 'g'),
      I('Olive oil', 'aceite de oliva virgen extra', 3, 'tbsp', true),
      I('Dried oregano', 'orégano', null, 'to taste', true),
    ],
    steps: [
      m('Knead flour, yeast, 380 ml water, salt and oil; rise 1 h (or use fridge dough from the morning).', 3600),
      m('Season the tomato with oregano and salt; prep toppings; oven to max with trays inside.'),
      c('Stretch bases thin, sauce + cheese + toppings, bake ~8 min each until blistered.', 480),
      c('Everyone builds their own — that is the rule.'),
    ],
  }),
  seed({
    id: 'lasagne', title: 'Lasagne al forno', cuisine: 'italian', prepMin: 30, cookMin: 45,
    tags: ['oven', 'weekend', 'kids-favourite'], kidScore: 0.9, season: ['autumn', 'winter'], kcal: 710, protein: 36, carbs: 52, fat: 38,
    tools: ['Oven dish', 'Two pots', 'Whisk'],
    ingredients: [
      I('Lasagne sheets', 'placas de lasaña', 12, 'count'),
      I('Mixed mince (beef/pork)', 'carne picada mixta', 600, 'g'),
      I('Crushed tomato', 'tomate triturado', 800, 'g'),
      I('Milk', 'leche semidesnatada', 800, 'ml'),
      I('Flour', 'harina de trigo', 60, 'g', true),
      I('Butter', 'mantequilla', 60, 'g', true),
      I('Grated cheese', 'queso rallado gouda', 150, 'g'),
      I('Onion', 'cebolla', 1, 'count'),
      I('Carrots', 'zanahoria', 1, 'count'),
    ],
    steps: [
      m('Soffritto: dice onion + carrot fine.'),
      c('Brown the mince with the soffritto, add tomato, simmer 20 min.', 1200),
      c('Béchamel: melt butter, whisk in flour, then milk until thick; season with nutmeg.'),
      c('Layer ragù / sheets / béchamel ×3, cheese on top; bake 190°C ~30 min.', 1800),
    ],
  }),
  seed({
    id: 'ragu-bolognese', title: 'Spaghetti al ragù (bolognese)', cuisine: 'italian', prepMin: 15, cookMin: 40,
    tags: ['pasta', 'kids-favourite'], kidScore: 1, kcal: 650, protein: 32, carbs: 70, fat: 26,
    tools: ['Large pot', 'Deep skillet'],
    ingredients: [
      I('Spaghetti', 'espaguetis', 400, 'g'),
      I('Mixed mince (beef/pork)', 'carne picada mixta', 500, 'g'),
      I('Crushed tomato', 'tomate triturado', 600, 'g'),
      I('Onion', 'cebolla', 1, 'count'),
      I('Carrots', 'zanahoria', 1, 'count'),
      I('Celery stick', 'apio', 1, 'count'),
      I('Parmesan', 'queso parmesano', 80, 'g'),
      I('Olive oil', 'aceite de oliva virgen extra', 3, 'tbsp', true),
    ],
    steps: [
      m('Dice onion, carrot and celery fine.'),
      c('Soften the soffritto in oil 8 min; brown the mince hard.', 480),
      c('Add tomato + a splash of water; simmer 25 min minimum.', 1500),
      c('Toss with just-drained spaghetti; parmesan at the table.'),
    ],
  }),
  seed({
    id: 'arrabbiata', title: "Penne all'arrabbiata", cuisine: 'italian', prepMin: 5, cookMin: 20,
    tags: ['pasta', 'veg', 'quick'], kidScore: 0.5, kcal: 520, protein: 15, carbs: 82, fat: 15,
    tools: ['Large pot', 'Skillet'],
    ingredients: [
      I('Penne', 'macarrones (penne)', 400, 'g'),
      I('Crushed tomato', 'tomate triturado', 600, 'g'),
      I('Garlic', 'ajo', 4, 'clove', true),
      I('Dried chilli (guindilla)', 'guindilla', 2, 'count', true),
      I('Fresh parsley', 'perejil fresco', 1, 'bunch'),
      I('Olive oil', 'aceite de oliva virgen extra', 4, 'tbsp', true),
      I('Parmesan', 'queso parmesano', 60, 'g'),
    ],
    steps: [
      m('Slice the garlic; chop the parsley.'),
      c('Sizzle garlic + chilli in oil; add tomato and simmer 12 min.', 720),
      c('Cook penne al dente, toss through the sauce with parsley.'),
      c('Parmesan for the grown-ups; a milder bowl set aside for the kids before the chilli goes in.'),
    ],
  }),
  seed({
    id: 'risotto-funghi', title: 'Risotto ai funghi', cuisine: 'italian', prepMin: 10, cookMin: 30,
    tags: ['rice', 'veg'], kidScore: 0.6, season: ['autumn'], kcal: 540, protein: 16, carbs: 68, fat: 22,
    tools: ['Wide pot', 'Ladle', 'Small pot'],
    ingredients: [
      I('Arborio/round rice', 'arroz redondo', 350, 'g'),
      I('Mushrooms', 'champiñones', 400, 'g'),
      I('Vegetable stock', 'caldo de verduras', 1.2, 'l'),
      I('Onion', 'cebolla', 1, 'count'),
      I('Dry white wine', 'vino blanco de cocina', 150, 'ml'),
      I('Parmesan', 'queso parmesano', 80, 'g'),
      I('Butter', 'mantequilla', 50, 'g', true),
    ],
    steps: [
      m('Slice the mushrooms; dice the onion; keep the stock hot on the back burner.'),
      c('Brown the mushrooms in half the butter; set aside.'),
      c('Soften onion, toast the rice 2 min, add wine, then stock a ladle at a time, ~18 min.', 1080),
      c('Beat in mushrooms, parmesan and remaining butter off the heat; rest 2 min.', 120),
    ],
  }),
  seed({
    id: 'pollo-parmigiana', title: 'Pollo alla parmigiana with orzo', cuisine: 'italian', prepMin: 20, cookMin: 30,
    tags: ['oven', 'kids-favourite'], kidScore: 0.9, kcal: 680, protein: 42, carbs: 54, fat: 30,
    tools: ['Oven dish', 'Skillet', 'Pot'],
    ingredients: [
      I('Chicken breast', 'pechuga de pollo', 600, 'g'),
      I('Breadcrumbs', 'pan rallado', 120, 'g', true),
      I('Eggs', 'huevos', 2, 'count'),
      I('Crushed tomato', 'tomate triturado', 400, 'g'),
      I('Mozzarella', 'mozzarella rallada', 200, 'g'),
      I('Orzo or short pasta', 'pasta orzo', 320, 'g'),
      I('Parmesan', 'queso parmesano', 60, 'g'),
      I('Olive oil', 'aceite de oliva virgen extra', 4, 'tbsp', true),
    ],
    steps: [
      m('Flatten the breasts; bread them (egg → crumbs + parmesan).'),
      c('Pan-fry the cutlets golden, 3 min per side.', 360),
      c('Top with tomato + mozzarella in the oven dish; bake 200°C ~12 min.', 720),
      c('Boil the orzo; serve under the chicken with the extra sauce.'),
    ],
  }),
  seed({
    id: 'gnocchi-pesto', title: 'Gnocchi al pesto with green beans', cuisine: 'italian', prepMin: 5, cookMin: 15,
    tags: ['pasta', 'veg', 'quick'], kidScore: 0.8, kcal: 560, protein: 16, carbs: 74, fat: 23,
    tools: ['Large pot', 'Skillet'],
    ingredients: [
      I('Fresh gnocchi', 'ñoquis frescos', 800, 'g'),
      I('Basil pesto', 'pesto de albahaca', 190, 'g'),
      I('Flat green beans', 'judía verde plana', 250, 'g'),
      I('Cherry tomatoes', 'tomate cherry', 250, 'g'),
      I('Parmesan', 'queso parmesano', 60, 'g'),
      I('Pine nuts (optional)', 'piñones', 30, 'g'),
    ],
    steps: [
      m('Trim and halve the beans; halve the tomatoes.'),
      c('Boil beans 5 min, add gnocchi to the same pot until they float, ~2 min.', 420),
      c('Toss with pesto, tomatoes and a splash of cooking water; top with parmesan and pine nuts.'),
    ],
  }),
  seed({
    id: 'carbonara', title: 'Spaghetti alla carbonara', cuisine: 'italian', prepMin: 10, cookMin: 15,
    tags: ['pasta', 'quick', 'kids-favourite'], kidScore: 0.9, kcal: 640, protein: 27, carbs: 70, fat: 28,
    tools: ['Large pot', 'Skillet', 'Mixing bowl'],
    ingredients: [
      I('Spaghetti', 'espaguetis', 400, 'g'),
      I('Pancetta or bacon lardons', 'bacon en taquitos', 200, 'g'),
      I('Eggs', 'huevos', 4, 'count'),
      I('Parmesan', 'queso parmesano', 100, 'g'),
      I('Black pepper', 'pimienta negra', null, 'to taste', true),
    ],
    steps: [
      m('Whisk eggs (2 whole + 2 yolks) with grated parmesan and lots of pepper.'),
      c('Crisp the pancetta gently; cook the spaghetti al dente.'),
      c('Off the heat, toss pasta with pancetta, then the egg mix + pasta water until creamy.'),
      c('No cream. Serve immediately.'),
    ],
  }),
  seed({
    id: 'minestrone', title: 'Minestrone with crusty bread', cuisine: 'italian', prepMin: 15, cookMin: 30,
    tags: ['soup', 'veg'], kidScore: 0.5, season: ['autumn', 'winter'], kcal: 420, protein: 15, carbs: 58, fat: 14,
    tools: ['Big soup pot', 'Chef knife'],
    ingredients: [
      I('Small pasta', 'pasta pequeña (fideos)', 150, 'g'),
      I('White beans (cooked jar)', 'alubias blancas cocidas', 400, 'g'),
      I('Carrots', 'zanahoria', 2, 'count'),
      I('Courgette', 'calabacín', 1, 'count'),
      I('Celery stick', 'apio', 1, 'count'),
      I('Onion', 'cebolla', 1, 'count'),
      I('Crushed tomato', 'tomate triturado', 400, 'g'),
      I('Vegetable stock', 'caldo de verduras', 1.2, 'l'),
      I('Baguette', 'barra de pan', 1, 'count'),
      I('Olive oil', 'aceite de oliva virgen extra', 3, 'tbsp', true),
    ],
    steps: [
      m('Dice all the vegetables evenly small.'),
      c('Soften onion, carrot, celery in oil 8 min; add courgette, tomato and stock.', 480),
      c('Simmer 15 min, add pasta + beans for the last 8; season well.', 900),
      c('Olive oil drizzle on top; bread for dunking.'),
    ],
  }),

  // ============================ GLOBAL (10) ============================
  seed({
    id: 'caesar-pollo', title: 'Ensalada César con pollo', cuisine: 'global', prepMin: 15, cookMin: 15,
    tags: ['salad', 'light', 'quick'], kidScore: 0.7, season: ['spring', 'summer'], kcal: 470, protein: 36, carbs: 22, fat: 27,
    tools: ['Grill pan', 'Salad bowl', 'Oven tray'],
    ingredients: [
      I('Chicken breast', 'pechuga de pollo', 500, 'g'),
      I('Romaine lettuce', 'lechuga romana', 2, 'count'),
      I('Caesar dressing', 'salsa césar', 150, 'ml'),
      I('Baguette (for croutons)', 'barra de pan', 0.5, 'count'),
      I('Parmesan', 'queso parmesano', 60, 'g'),
      I('Olive oil', 'aceite de oliva virgen extra', 2, 'tbsp', true),
    ],
    steps: [
      m('Tear the bread, toss in oil, bake 200°C ~8 min into croutons.', 480),
      m('Wash and chop the romaine.'),
      c('Griddle the seasoned chicken ~6 min per side; rest and slice.', 720),
      c('Toss leaves with dressing, top with chicken, croutons and parmesan shavings.'),
    ],
  }),
  seed({
    id: 'chili-con-carne', title: 'Chili con carne with rice', cuisine: 'global', prepMin: 10, cookMin: 35,
    tags: ['stew', 'batch-cook'], kidScore: 0.7, season: ['autumn', 'winter'], kcal: 620, protein: 34, carbs: 62, fat: 24,
    tools: ['Deep pot', 'Small pot'],
    ingredients: [
      I('Beef mince', 'carne picada de ternera', 500, 'g'),
      I('Red kidney beans (jar)', 'alubias rojas cocidas', 400, 'g'),
      I('Crushed tomato', 'tomate triturado', 600, 'g'),
      I('Onion', 'cebolla', 1, 'count'),
      I('Red pepper', 'pimiento rojo', 1, 'count'),
      I('White rice', 'arroz largo', 320, 'g'),
      I('Cumin + smoked paprika', 'comino molido', 2, 'tsp', true),
      I('Olive oil', 'aceite de oliva virgen extra', 2, 'tbsp', true),
    ],
    steps: [
      m('Dice the onion and pepper.'),
      c('Brown the mince hard; add onion, pepper and spices for 4 min.', 240),
      c('Add tomato + beans, simmer 25 min; cook the rice meanwhile.', 1500),
      c('Serve on rice — yogurt on top tames it for the kids.'),
    ],
  }),
  seed({
    id: 'tacos-pollo', title: 'Tacos de pollo (build-your-own)', cuisine: 'global', prepMin: 15, cookMin: 15,
    tags: ['kids-favourite', 'fun', 'quick'], kidScore: 1, kcal: 590, protein: 34, carbs: 56, fat: 25,
    tools: ['Skillet', 'Small bowls for toppings'],
    ingredients: [
      I('Chicken breast', 'pechuga de pollo', 600, 'g'),
      I('Tortilla wraps', 'tortillas de trigo', 12, 'count'),
      I('Taco seasoning', 'sazonador para tacos', 1, 'count'),
      I('Sweetcorn', 'maíz dulce', 150, 'g'),
      I('Tomatoes', 'tomate pera', 3, 'count'),
      I('Grated cheese', 'queso rallado gouda', 150, 'g'),
      I('Lettuce', 'lechuga romana', 1, 'count'),
      I('Sour cream or yogurt', 'nata agria', 200, 'ml'),
    ],
    steps: [
      m('Slice the chicken into strips and toss with the seasoning.'),
      m('Dice tomatoes; shred lettuce; set out all toppings in bowls.'),
      c('Sear the chicken ~7 min until charred at the edges; warm the tortillas.', 420),
      c('Everyone builds their own at the table.'),
    ],
  }),
  seed({
    id: 'burgers-caseros', title: 'Homemade burgers with wedges', cuisine: 'global', prepMin: 15, cookMin: 25,
    tags: ['kids-favourite', 'weekend'], kidScore: 1, kcal: 750, protein: 38, carbs: 60, fat: 38,
    tools: ['Skillet or grill pan', 'Oven tray', 'Mixing bowl'],
    ingredients: [
      I('Beef mince', 'carne picada de ternera', 600, 'g'),
      I('Burger buns', 'pan de hamburguesa', 4, 'count'),
      I('Potatoes (for wedges)', 'patata', 800, 'g'),
      I('Cheddar slices', 'queso cheddar en lonchas', 4, 'count'),
      I('Tomatoes', 'tomate pera', 2, 'count'),
      I('Lettuce', 'lechuga romana', 1, 'count'),
      I('Ketchup + mayo', 'ketchup', null, 'to taste', true),
      I('Olive oil', 'aceite de oliva virgen extra', 2, 'tbsp', true),
    ],
    steps: [
      m('Cut potatoes into wedges, oil + salt, oven 210°C ~25 min.', 1500),
      m('Shape 4 patties, salt just before cooking; slice tomato, wash lettuce.'),
      c('Sear patties 3–4 min per side, cheese on for the last minute; toast the buns.', 480),
      c('Build and serve with the wedges.'),
    ],
  }),
  seed({
    id: 'pad-thai-pollo', title: 'Chicken pad thai', cuisine: 'global', prepMin: 15, cookMin: 15,
    tags: ['noodles', 'quick'], kidScore: 0.7, kcal: 600, protein: 32, carbs: 68, fat: 22,
    tools: ['Wok', 'Tongs'],
    ingredients: [
      I('Rice noodles', 'fideos de arroz', 300, 'g'),
      I('Chicken breast', 'pechuga de pollo', 400, 'g'),
      I('Eggs', 'huevos', 2, 'count'),
      I('Bean sprouts', 'brotes de soja', 200, 'g'),
      I('Peanuts', 'cacahuetes tostados', 60, 'g'),
      I('Fish sauce', 'salsa de pescado', 3, 'tbsp'),
      I('Sugar', 'azúcar', 2, 'tbsp', true),
      I('Lime', 'lima', 2, 'count'),
      I('Spring onions', 'cebolleta', 1, 'bunch'),
    ],
    steps: [
      m('Soak the noodles per the packet; mix fish sauce, sugar and juice of 1 lime.'),
      c('Stir-fry the chicken hot; push aside and scramble the eggs in the wok.'),
      c('Add noodles + sauce, toss 2 min; fold in sprouts and spring onion.', 120),
      c('Top with crushed peanuts and lime wedges.'),
    ],
  }),
  seed({
    id: 'curry-garbanzos', title: 'Chickpea & spinach curry with rice', cuisine: 'global', prepMin: 10, cookMin: 25,
    tags: ['veg', 'legumes'], kidScore: 0.6, kcal: 520, protein: 18, carbs: 70, fat: 19,
    tools: ['Deep skillet', 'Small pot'],
    ingredients: [
      I('Cooked chickpeas (jar)', 'garbanzos cocidos', 800, 'g'),
      I('Spinach', 'espinacas frescas', 200, 'g'),
      I('Coconut milk', 'leche de coco', 400, 'ml'),
      I('Crushed tomato', 'tomate triturado', 400, 'g'),
      I('Onion', 'cebolla', 1, 'count'),
      I('Curry powder', 'curry en polvo', 2, 'tbsp', true),
      I('White rice', 'arroz largo', 320, 'g'),
      I('Garlic', 'ajo', 2, 'clove', true),
    ],
    steps: [
      m('Dice the onion; drain the chickpeas; start the rice.'),
      c('Soften onion + garlic, bloom the curry powder 1 min.'),
      c('Add tomato, coconut milk and chickpeas; simmer 15 min.', 900),
      c('Wilt in the spinach at the end; serve over rice.'),
    ],
  }),
  seed({
    id: 'salmon-horno', title: 'Baked salmon, potatoes & green beans', cuisine: 'global', prepMin: 10, cookMin: 30,
    tags: ['fish', 'oven', 'one-pan'], kidScore: 0.7, kcal: 560, protein: 34, carbs: 42, fat: 27,
    tools: ['Oven tray', 'Chef knife'],
    ingredients: [
      I('Salmon fillets', 'lomos de salmón', 4, 'count'),
      I('Baby potatoes', 'patata nueva', 800, 'g'),
      I('Flat green beans', 'judía verde plana', 300, 'g'),
      I('Lemon', 'limón', 1, 'count'),
      I('Garlic', 'ajo', 3, 'clove', true),
      I('Olive oil', 'aceite de oliva virgen extra', 3, 'tbsp', true),
      I('Fresh dill or parsley', 'eneldo fresco', 1, 'bunch'),
    ],
    steps: [
      m('Halve the potatoes, toss with oil + salt, roast 200°C for 15 min head start.', 900),
      c('Add beans and salmon to the tray with lemon slices + garlic; back in 12 min.', 720),
      c('Scatter herbs, squeeze the roasted lemon over, serve from the tray.'),
    ],
  }),
  seed({
    id: 'wraps-pollo', title: 'Chicken & veg wraps', cuisine: 'global', prepMin: 15, cookMin: 10,
    tags: ['quick', 'kids-favourite'], kidScore: 0.9, kcal: 540, protein: 32, carbs: 52, fat: 22,
    tools: ['Skillet', 'Chopping board'],
    ingredients: [
      I('Chicken breast', 'pechuga de pollo', 500, 'g'),
      I('Tortilla wraps', 'tortillas de trigo', 8, 'count'),
      I('Red pepper', 'pimiento rojo', 1, 'count'),
      I('Avocado', 'aguacate', 2, 'count'),
      I('Grated cheese', 'queso rallado gouda', 100, 'g'),
      I('Yogurt (for the sauce)', 'yogur griego natural', 125, 'g'),
      I('Lettuce', 'lechuga romana', 1, 'count'),
    ],
    steps: [
      m('Slice chicken and pepper; smash the avocado with salt; mix yogurt with a little garlic.'),
      c('Sear chicken + pepper strips ~8 min; warm the wraps.', 480),
      c('Assemble at the table: sauce, lettuce, chicken, avocado, cheese, roll and eat.'),
    ],
  }),
  seed({
    id: 'shakshuka', title: 'Shakshuka with bread', cuisine: 'global', prepMin: 10, cookMin: 20,
    tags: ['veg', 'one-pan', 'quick'], kidScore: 0.6, kcal: 430, protein: 20, carbs: 34, fat: 24,
    tools: ['Skillet with lid'],
    ingredients: [
      I('Eggs', 'huevos', 6, 'count'),
      I('Crushed tomato', 'tomate triturado', 800, 'g'),
      I('Red pepper', 'pimiento rojo', 1, 'count'),
      I('Onion', 'cebolla', 1, 'count'),
      I('Cumin + smoked paprika', 'comino molido', 2, 'tsp', true),
      I('Feta (optional)', 'queso feta', 100, 'g'),
      I('Baguette', 'barra de pan', 1, 'count'),
      I('Olive oil', 'aceite de oliva virgen extra', 3, 'tbsp', true),
    ],
    steps: [
      m('Slice the onion and pepper.'),
      c('Soften them in oil 8 min with the spices; add tomato, simmer 8 min.', 960),
      c('Make wells, crack in the eggs, lid on 5 min until just set.', 300),
      c('Crumble feta over; eat from the pan with bread.'),
    ],
  }),
  seed({
    id: 'couscous-verduras', title: 'Couscous with roast vegetables & chicken', cuisine: 'global', prepMin: 15, cookMin: 25,
    tags: ['light', 'oven'], kidScore: 0.6, kcal: 550, protein: 30, carbs: 64, fat: 20,
    tools: ['Oven tray', 'Heatproof bowl'],
    ingredients: [
      I('Couscous', 'cuscús', 300, 'g'),
      I('Chicken thighs, boneless', 'contramuslos de pollo', 500, 'g'),
      I('Courgette', 'calabacín', 1, 'count'),
      I('Red pepper', 'pimiento rojo', 1, 'count'),
      I('Red onion', 'cebolla morada', 1, 'count'),
      I('Chicken stock', 'caldo de pollo', 350, 'ml'),
      I('Raisins (optional)', 'pasas sultanas', 50, 'g'),
      I('Ras el hanout or curry powder', 'ras el hanout', 2, 'tsp', true),
      I('Olive oil', 'aceite de oliva virgen extra', 3, 'tbsp', true),
    ],
    steps: [
      m('Chunk the vegetables and chicken; toss with oil + spices on the tray.'),
      c('Roast at 210°C ~22 min until charred at the edges.', 1320),
      c('Pour hot stock over the couscous, cover 5 min, fluff with a fork; fold in raisins.', 300),
      c('Pile the tray over the couscous, juices included.'),
    ],
  }),
];
